### ISSUE TITLE
Provide report / slide for Ravi and Paulo detailing status of data collection

### ISSUE THREAD

**Issue by sktylr** [ias-tcd/competitor-matching-model#50]

**Comment by temi-oye** [comment]
Link to doc https://docs.google.com/document/d/1X0X1rR6j90HIq_xxtypPZH3hX2oDObPtKQppvoJn1wU/edit?usp=sharing (wip)

**Comment by temi-oye** [comment]
@sktylr do you have any thoughts on the document above? I figured that since the client meeting is tomorrow it might be better to ask the questions during the meeting as opposed to doing it over discord.

**Comment by tech-xelda** [comment]
@temi-oye doc looks good 👍. I'd also be interested in how we should go about labelling etc so would be god to ask tomorrow
