### ISSUE TITLE
Filter out bboxes with confidence less than a configurable threshold

### ISSUE THREAD

**Issue by sktylr** [ias-tcd/competitor-matching-model#65]
Have a look at the `conf_thres` variable in the `Detector` class. We should be able to increase this from the default value of 0.1 to a larger confidence value to rule out bboxes that probably aren't logos.

Let's start with a confidence of 0.5

**Comment by liuphui** [comment]
Should I prioritise actual logos with low confidence score or filter out the ones that aren't actually logos? For example, if the model detects the adidas logo with confidence score of 0.22 and it detects the fake logo with confidence of 0.4, should I set conf_thres as 0.23 or 0.41?

**Comment by sktylr** [comment]
Yeah good question. I'd be inclined to prioritise the actual logos. Hopefully combined with the ANN search and possible further training of the model with the images the data collection team gather we will see higher confidences for actual logos in the future compared with the non-logos

**Comment by liuphui** [comment]
Great, do I just test and change the conf_thres value in Detector?

**Comment by sktylr** [comment]
Yeah exactly, maybe use the images Fintan collected at the start as a base line and see what confidence value works best as a threshold, you can document this if you want for any future parameter adjustments we make. I found that Nike logos weren't picked up very well so you may find you need to pick a threshold that rules out most nike logos but works for all other brands etc.
